server:
  port: 9899
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://49.234.146.117:3306/db01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
          username: root
          password: '0913'
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            minimum-idle: 50
            idle-timeout: 600000
            maximum-pool-size: 100
            connection-timeout: 60000

mybatis-plus:
  type-aliases-package: com.lhm.testdemo.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    banner: false
